# Generated by Django 6.0.6 on 2026-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('gas_leak', 'Gas Leak'), ('fire', 'Fire / Flame'), ('water_low', 'Water Tank Level Low'), ('overcurrent', 'Current Overload'), ('intrusion', 'Motion / Intrusion'), ('window_open', 'Window / Door Open'), ('vibration', 'Vibration / Seismic'), ('rfid_denied', 'RFID Access Denied'), ('system', 'System / Hardware Fault'), ('car_detected', 'Vehicle Detected at Garage')], max_length=20),
        ),
    ]
