web: daphne -b 0.0.0.0 -p $PORT smartnest.asgi:application
worker: celery -A smartnest worker -l info
beat: celery -A smartnest beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler