# Generated by Django 5.0.6 on 2026-06-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('anomaly_detector', 'Anomaly Detector (Isolation Forest)'), ('gas_classifier', 'Gas Severity Classifier (Random Forest)'), ('earthquake_classifier', 'Earthquake vs Vibration (SVM)'), ('occupancy_predictor', 'Occupancy Predictor (Logistic Regression)'), ('energy_forecaster', 'Energy Forecaster (Linear Regression)')], max_length=30)),
                ('input_data', models.JSONField(help_text='Feature values fed into the model for this prediction')),
                ('prediction', models.CharField(help_text="e.g. 'anomaly', 'gas_leak', 'will_stay'", max_length=100)),
                ('confidence', models.FloatField(blank=True, help_text='0-1 score, blank for regression outputs', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
