# Generated by Django 5.0.6 on 2026-06-30 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(blank=True, help_text='Card UID, blank if keypad entry', max_length=50)),
                ('method', models.CharField(choices=[('rfid', 'RFID Card'), ('keypad', 'Keypad PIN')], max_length=10)),
                ('granted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('esp32_main', 'ESP32 Main Board'), ('door_lock', 'Door Lock (Servo)'), ('fan', 'Fan (Relay)'), ('light', 'Light (Relay)'), ('ventilation', 'Ventilation Fan (Relay)'), ('buzzer', 'Buzzer'), ('other', 'Other')], default='other', max_length=30)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="e.g. 'unlock_door', 'fan_on', 'light_off'", max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Extra parameters for the action')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_duration_mins', models.FloatField(default=0)),
                ('estimated_kwh', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_logs', to='devices.device')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('device', 'date')},
            },
        ),
    ]
