# Generated by Django 5.0.6 on 2026-06-30 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature (DHT11)'), ('humidity', 'Humidity (DHT11)'), ('distance', 'Distance (HC-SR04)'), ('motion', 'Motion (PIR)'), ('gas_mq2', 'Gas/Smoke (MQ-2)'), ('gas_mq7', 'Carbon Monoxide (MQ-7)'), ('flame', 'Flame Sensor'), ('light', 'Light Level (LDR)'), ('door_state', 'Door/Window (Reed Switch)')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_type', '-timestamp'], name='sensors_sen_sensor__6403aa_idx')],
            },
        ),
    ]
