# Generated by Django 6.0.6 on 2026-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensorreading_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('distance', 'Ultrasonic Distance'), ('motion', 'PIR Motion'), ('window', 'Reed Switch / Window'), ('gas', 'MQ-2 Gas'), ('flame', 'Flame Sensor'), ('water_level', 'Water Tank Level (%)'), ('current', 'ACS712 Current'), ('light', 'LDR Light Level'), ('vibration', 'MPU6050 Vibration'), ('light_relay', 'Light Relay State'), ('fan_relay', 'Fan Relay State'), ('cutoff_relay', 'Cutoff Relay State'), ('car_presence', 'Garage Ultrasonic — Vehicle Presence')], max_length=20),
        ),
    ]
